#!/usr/bin/env bash
#script transfers files from client to server
# -i: selects file from which identity (private key) for public key authentication is read
IP=$2
USERNAME=$3
FILE=$1
KEY_PATH=$4

if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$KEY_PATH" -o StrictHostKeyChecking=no "$FILE" "$USERNAME"@"$IP":~/
fi
