#!/usr/bin/env bash
# redirects to another page "301 Moved Permanently"
sudo apt-get update;
sudo apt-get -y install nginx;
newString="rewrite ^\/redirect_me\/ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
file="/etc/nginx/sites-available/default"
sudo sed -i "26i $new_string" $file;
sudo service nginx start;
