#!/usr/bin/env bash
# redirects to another page "301 Moved Permanently"
sudo apt-get update;
sudo apt-get -y install nginx;
new_string="rewrite ^/redirect_me http://motherfuckingwebsite.com/ permanent;"
file="/etc/nginx/sites-enabled/default"
sudo sed -i "26i $new_string" $file;
sudo service nginx start;
