#!/usr/bin/env bash
# configures Nginx server to have custom 404 page that contains string "Ceci n'est pas une page"
sudo apt-get update
sudo apt-get install -y nginx
echo -e "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
newString="error_page 404 /custom_404.html;\\n location = /custom_404.html {\\n root /usr/share/nginx/html;\\n internal;\\n}"
myMatch="#error_page 404 /404.html;"
file="/etc/nginx/sites-enabled/default"
sudo sed -i "s$myMatch $newString" $file
sudo service nginx start;
