#!/usr/bin/env bash
# redirects to another page "301 Moved Permanently"
sudo apt-get update;
sudo apt-get -y install nginx;
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
newString="error_page 404 /custom_404.html;\\n location = /custom_404.html {\\n root /usr/share/nginx/html;\\n internal;\\n}"
myMatch="#error_page 404 /404.html;"
file="/etc/nginx/sites-enabled/default"
sudo sed -i "26i $new_string" $file;
sudo service nginx start;
