#!/bin/bash
# mkdir action $PATH - this is the idea, but how do I create a directory in $PATH?
export -p PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/action"

