#!/usr/bin/env bash
# this changes the ownership priveleges of nginx
pkill apache2
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
chown -R nginx /var/log/nginx/ /etc/nginx/ /usr/share/nginx/
chmod 755 /etc/nginx/nginx.conf
su nginx -c nginx
