#!/usr/bin/env bash
# this doubles the number of webservers we have
sudo apt-get update
sudo apt-get install -y nginx
echo "Holberton School 2" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "26i add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx start;
