#!/usr/bin/env bash
#this installs and configures HAproxy on our lb-01 server
sudo apt-get update
sudo apt-get install haproxy
#enable HAProxy to be started by init script enabling to option 1
sudo sed -i "ENABLED=1" /etc/default/haproxy
sudo sed -i "\nlisten appname 0.0.0.0:80\n\tbalance roundrobin\n\toptionhttpclose\n\toptionforwardfor\n\tserver 65-web-01 54.91.75.76:80 check\n\tserver 65-web-02 52.207.18.140:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
