#!/usr/bin/env bash
#this installs and configures HAproxy on our lb-01 server
sudo apt-get update
sudo apt-get install haproxy
#enable HAProxy to be started by init script enabling to option 1
sudo sed "ENABLED=1" /etc/default/haproxy
sudo sed "\nlisten appname 0.0.0.0:80\n balance roundrobin\n optionhttpclose\n optionforwardfor\n server lamp1 10.0.0.1:80 check\nserver lamp2 10.0.0.2:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
