#!/usr/bin/env bash
# this displays 'To infinity and beyond' indefinetly adding 'sleep 2' second pauses in between iterations
# 'I am invincible!!!' when receiving a SIGTERM
trap "echo I am invincible!!!" SIGTERM

while :
do
	echo "To infinity and beyond"
	sleep 2

done
