#!/usr/bin/env bash
# Prints ascending numbers  except on 4th, 8th and 17th iterations

i="1"

while [ $i -le 20 ]
do
	echo $i
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "good luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	i=$((i + 1))
done
