#!/usr/bin/env bash
# this configures Ubuntu server with reqs
cp /etc/hosts ~/hosts.new
sudo sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sudo sed -i '$ a8.8.8.8 facebook.com/' ~/hosts.new
cp ~/hosts.new /etc/hosts
