#!/usr/bin/env bash
# Prints "FizzBuzz" on multiples of 3 & 5, "Fizz" on multiples of 3, "Buzz" on multiples of 5

i="1"

while [ $i -le 100 ]
do
	i=$((i + 1))
	echo $i
	if [ $i % 15 == "0" ]
		then echo "FizzBuzz"
	elif [ $i % 3  == "0" ]
		then echo "Fizz"
	else [ $i % 5 == "0" ]
		echo "Buzz";
	fi
done
