#!/usr/bin/env bash
# Prints "Holberton School" except on 4th ("bad luck") and 8th ("good luck") iteration

i="1"

while [ $i -le 8 ]
do
	echo "Holberton School"
	i=$((i + 1))
	if [ $i == "4" ]
		then echo "bad luck"
	elif [ $i == "7" ]
		then echo "good luck"
	fi
done
