#!/usr/bin/env bash
# Prints ascending numbers  except on 4th, 8th and 17th iterations

i="0"

while [ $i -le 19 ]
do
	i=$((i + 1))
	echo $i
	case $i in
		"4")
		echo "bad luck from China"
		;;
		"9")
		echo "good luck from Japan"
		;;
		"17")
		echo "bad luck from Italy"
	esac
done
